config/routes.rb
Rails.application.routes.draw do
  get 'statics/index'

  get 'statics/about'

  devise_for :users
	resources :comentarios
	resources :peliculas 

  get 'comentarios/index'

  get 'peliculas/index'


root :to => "statics#index"

get 'statics/index'

get 'statics/about'
get '/about' => 'statics#about', :as => :about
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

	 def index
      @comentarios = Comentario.all
   end
   
   def show
       @comentario = Comentario.find(params[:id])
   end
   
   def new
       @comentario = Comentario.new
   end
   
   def create
       @comentario = Comentario.new(com_params)

      if @comentario.save
         redirect_to comentarios_path, notice => "Se ha guardado la comentario"
      else
         render "new"
   end
   end
   

private
   def com_params
      params.require(:comentario).permit(:name, :stars, :main_actor, :year)
   end

end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
 
	 def index
      @peliculas = Pelicula.all
   end
   
   def show
       @pelicula = Pelicula.find(params[:id])
   end
   
   def new
       @pelicula = Pelicula.new
   end
   
   def create
       @pelicula = Pelicula.new(peli_params)

      if @pelicula.save
         redirect_to peliculas_path, notice => "Se ha guardado la pelicula"
      else
         render "new"
   end
   end
   

private
   def peli_params
      params.require(:pelicula).permit(:name, :stars, :main_actor, :year)
   end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/comentarios/edit.html.erb
<h1>Ciudades#edit</h1>
<p>Find me in app/views/comentarios/index.html.erb</p>

app/views/comentarios/index.html.erb
<div class="container">
<h2 class="jumbotron"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Index</h2>
<div class="list-group" style="width:70%; margin: 0px auto;">
<h3 class="list-group-item active">Listado de Comentarios</h3>
<% @comentarios.each do |com| %>
    <br>
	<p class="list-group-item">ID: <%= com.id %></p>
	<p class="list-group-item">Titulo: <%= link_to com.name, com %></p>
	<p class="list-group-item">Cadena: <%= com.stars %></p>
	<p class="list-group-item">Presentador: <%= com.main_actor %></p>
	<p class="list-group-item">Horario: <%= com.year %></p>
<% end %>
<br>
<p><%=link_to "Añadir comentario", new_comentario_path, class:"btn btn-md btn-success" %></p>
</div>
</div>    

app/views/comentarios/new.html.erb
<div class="container">
	<h2>Añade aqui un nuevo comentario</h2>


<%= form_for @comentario do |comentario| %>
 

<p>
	<%= comentario.label :name %> <br/>
	<%= comentario.text_field :name %>
</p>

<p>
	<%= comentario.label :stars %> <br/>
	<%= comentario.text_field :stars %>
</p>

<p>
	<%= comentario.label :main_actor %> <br/>
	<%= comentario.text_field :main_actor %>
</p>

<p>
	<%= comentario.label :year %> <br/>
	<%= comentario.text_field :year %>
</p>
<%= comentario.submit "Añadir comentario",  class:"btn btn-md btn-danger" %>

<% end %>
<br>
<p> <%= link_to "Back", comentarios_path, class:"btn btn-md btn-success" %> </p>

</div>

app/views/comentarios/show.html.erb
<div class="container">
<h2 class="jumbotron"><span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Mostrar Comentario</h2>

<div class="list-group" style="width:70%; margin: 0px auto;">
<p class="list-group-item">ID: <%= @comentario.id %></p>
<p class="list-group-item">Titulo: <%= @comentario.name %></p>
<p class="list-group-item">Cadena: <%= @comentario.stars %></p>
<p class="list-group-item">Presentador: <%= @comentario.main_actor %></p>
<p class="list-group-item">Horario: <%= @comentario.year %></p>
<br>
<%= link_to "Back",  comentarios_path, class:"btn btn-md btn-success" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peliculas/edit.html.erb
<h1>Ciudades#edit</h1>
<p>Find me in app/views/peliculas/index.html.erb</p>

app/views/peliculas/index.html.erb
<div class="container">
<h2 class="jumbotron"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Index</h2>
<div class="list-group" style="width:70%; margin: 0px auto;">
<h3 class="list-group-item active">Listado de Peliculas</h3>
<% @peliculas.each do |peli| %>
    <br>
	<p class="list-group-item">ID: <%= peli.id %></p>
	<p class="list-group-item">Titulo: <%= link_to peli.name, peli %></p>
	<p class="list-group-item">Cadena: <%= peli.stars %></p>
	<p class="list-group-item">Presentador: <%= peli.main_actor %></p>
	<p class="list-group-item">Horario: <%= peli.year %></p>
<% end %>
<br>
<p><%=link_to "Añadir pelicula", new_pelicula_path, class:"btn btn-md btn-success" %></p>
</div>
</div>       

app/views/peliculas/new.html.erb
<div class="container">
	<h2>Añade aqui una nueva pelicula</h2>


<%= form_for @pelicula do |pelicula| %>
 

<p>
	<%= pelicula.label :name %> <br/>
	<%= pelicula.text_field :name %>
</p>

<p>
	<%= pelicula.label :stars %> <br/>
	<%= pelicula.text_field :stars %>
</p>

<p>
	<%= pelicula.label :main_actor %> <br/>
	<%= pelicula.text_field :main_actor %>
</p>

<p>
	<%= pelicula.label :year %> <br/>
	<%= pelicula.text_field :year %>
</p>
<%= pelicula.submit "Añadir pelicula",  class:"btn btn-md btn-danger" %>

<% end %>
<br>
<p> <%= link_to "Back", peliculas_path, class:"btn btn-md btn-success" %> </p>

</div>  

app/views/peliculas/show.html.erb
<div class="container">
<h2 class="jumbotron"><span class="glyphicon glyphicon-search"></span>&nbsp;&nbsp;Mostrar Peliculas</h2>

<div class="list-group" style="width:70%; margin: 0px auto;">
<p class="list-group-item">ID: <%= @pelicula.id %></p>
<p class="list-group-item">Titulo: <%= @pelicula.name %></p>
<p class="list-group-item">Cadena: <%= @pelicula.stars %></p>
<p class="list-group-item">Presentador: <%= @pelicula.main_actor %></p>
<p class="list-group-item">Horario: <%= @pelicula.year %></p>
<br>
<%= link_to "Back",  peliculas_path, class:"btn btn-md btn-success" %>
</div>
</div>

app/views/shared/_header.html.erb
<div class="container">
	<div class="header1">
		<div class="col-md-6 col-xs-6 col-lg-6" align="left">
		<h2><u>Rotten Tomaco</u></h2><img typeof="foaf:Image" itemprop="image" src="https://vignette4.wikia.nocookie.net/non-aliencreatures/images/6/6e/Tomacco.png/revision/latest?cb=20150206223636" width="200" height="100">
		<img typeof="foaf:Image" itemprop="image" src="http://media.gettyimages.com/photos/film-reel-and-movie-clapper-board-video-icon-3d-render-picture-id492854506?s=170667a&amp;w=1007" width="100"height="100">

<a href="http://www.quondos.com?ap_id=gmkt20" target="_blank"><img src="http://www.quondos.com/wp-content/uploads/affiliates/Banners_468x60.jpg" alt="Quondos" border="0" align="right"></a>
	
		<div class="col-md-6 col-xs-6 col-lg-6" align="right" >
			<p><b>Todas las peliculas disponibles en HD, Blue-ray i en screener.
			Toda la selecion de estilos para gaudir de una buena pelicula disfrutandola en casa.</b></p>
		<br>
		<br>
		
<ul class="headertxt">
	<button type="button"><a href="#news">MOVIES & DVDS</a></button>
          <button type="button"><a href="#news">TV</a></button>
          <button type="button"><a href="#news">NEWS</a></button>
          <button type="button"><a href="#about">TICKETS & SHOWTIMES</a></button>
      </ul>

		</div>
</div>

app/views/statics/about.html.erb
<h1>Statics#about</h1>
<p>find me in app/views/statics/about.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>